### ISSUE TITLE
Which optical flow algorithm is used?

### ISSUE THREAD

**Issue by happyCodingSusan** [Tencent/ActionDetection-DBG#13]
Great work! Thanks for sharing!! 

To generate optical flow, do you use dense flow from https://github.com/yjxiong/anet2016-cuhk use denseFlow or https://github.com/feichtenhofer/gpu_flow same as BSN author? Wonder which one is better.

**Comment by lijiannuist** [comment]
We use dense flow from https://github.com/yjxiong/anet2016-cuhk
You can refer to ./tools/extract_optical_flow.sh

**Comment by happyCodingSusan** [comment]
Thank you very much for your kind reply!
