### ISSUE TITLE
The generation time overlaps!!!

### ISSUE THREAD

**Issue by gtgtgt1117** [Tencent/ActionDetection-DBG#8]
@lijiannuist 
hello,我想问一下,proposals是在PFG生成的是吗?那个时间生成一定是会有重叠的是吧?

**Comment by lijiannuist** [comment]
Hi @gtgtgt1117 
对于100长特征而言，proposals的数量是固定的，有100*100/2，PFG layer其实是生成这些个proposals的特征，这些个proposals肯定是有重叠的，靠后面的两个分支进行打分和后处理去重。

**Comment by gtgtgt1117** [comment]
> Hi @gtgtgt1117
> 对于100长特征而言，proposals的数量是固定的，有100*100/2，PFG layer其实是生成这些个proposals的特征，这些个proposals肯定是有重叠的，靠后面的两个分支进行打分和后处理去重。

Thank   you .但是我并不是很理解100*100/2.
那这个可以用于实际场景的检测吗?我的测试结果并不是很好(指的是时间段和实际不是很符合)

**Comment by gtgtgt1117** [comment]
@lijiannuist Hi,proposals的个数应该是1-100的和吧(5050个)? 在后处理中通过top_number来设置最后保留的proposals个数是不?

**Comment by lijiannuist** [comment]
@gtgtgt1117 
是的，一般还需要卡一个分数阈值来保留。

**Comment by gtgtgt1117** [comment]
> @gtgtgt1117
> 是的，一般还需要卡一个分数阈值来保留。

Thank you
