### ISSUE TITLE
When will train.py be released?

### ISSUE THREAD

**Issue by Light--** [Tencent/ActionDetection-DBG#9]
Thanks for sharing the project!
Recently, I was learning DBG papers and codes,  really want to try training with my own dataset. May i ask the **time schedule** of releasing the traing codes (```train.py```)?

**Comment by linchuming** [comment]
Hi, thanks for your attention. We have released training code today!

**Comment by Light--** [comment]
> Hi, thanks for your attention. We have released training code today!

Btw, cannot access your [website](cmlin.cn), huh~
